name: Docker Build & Deploy to GCP Artifact Registry

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev

      - name: Build and push image to GAR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: asia-northeast3-docker.pkg.dev/liquid-braid-463809-s5/fastapi/fastapi-app:latest

      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: dev.yeachan
          key: ${{ secrets.SSH_KEY }}
          script: |
            gcloud auth configure-docker asia-northeast3-docker.pkg.dev
            docker pull asia-northeast3-docker.pkg.dev/liquid-braid-463809-s5/fastapi/fastapi-app:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d --name fastapi-app -p 8000:8000 \
              -v /home/dev.yeachan/gcpkey.json:/app/gcpkey.json \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/gcpkey.json \
              -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
              -e DB_USER=${{ secrets.DB_USER }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_PORT=${{ secrets.DB_PORT }} \
              -e DB_NAME=${{ secrets.DB_NAME }} \
              -e GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} \
              asia-northeast3-docker.pkg.dev/liquid-braid-463809-s5/fastapi/fastapi-app:latest
